### ISSUE TITLE
Debug adapter disconnected

### ISSUE THREAD

**Issue by Monirzadeh** [jbyuki/one-small-step-for-vimkind#20]
I have two files
1. test file that write with busted - `test.lua`
2. my code - `mycode.lua`

I run server than set breakpoint inside `mycode.lua`. But when I run `lua require"dap".continue()` it gets me this massage 'session active but not stopped at breakpoint'
I run `lua require"osv".run_this()`  sometime it work and stop in breakpoint but get this massage `Debug adapter diconnected`
do i something wrong?
Can you add more example to documentation?

**Comment by jbyuki** [comment]
I'm not completely sure what the problem is with the given informations but i can point you to several "hidden" documentation which could maybe solve your problem.

* There is a plugin internal documentation [here](https://github.com/jbyuki/one-small-step-for-vimkind/blob/main/doc/osv.txt) which a complete step-by-step instruction example in the Quickstart section.
* A video example of debugging the telescope plugin [here](https://github.com/jbyuki/one-small-step-for-vimkind/issues/7#issuecomment-925273710)
* There is some documentation on internet like [this one](https://alpha2phi.medium.com/neovim-lsp-and-dap-using-lua-3fb24610ac9f)
* Note that this plugin is primarily intended to debug neovim plugins and not just lua scripts. Otherwise something like [lua-debug](https://github.com/actboy168/lua-debug) would be more appropriate.

**Comment by jbyuki** [comment]
If you provide me with a way to reproduce the problem on my side, I may be able to give a solution.

**Comment by Monirzadeh** [comment]
Maybe I am wrong about this project
I need a debugger that can attach to nvim-dap to debug my Lua project, not debug neovim plugins.
[lua-debug](https://github.com/actboy168/lua-debug) can't connect to nvim (maybe I am wrong again)
but in general I have a Lua script with tests that I want to debug

As I read lua-debug repository, I can't use that with nvim-dap. Can you suggest something else?
I am sorry for wrong issue. Thanks for your help

**Comment by jbyuki** [comment]
The problem is that osv (one-small-step-for-vimkind) uses the neovim's own interpreter so you might not be able to require external dependencies installed with luarocks, if it's the case. If you can run your project with neovim's lua interpreter, then osv might be able to help you. In case of doubt you could also start osv with logging turned on and inspect `osv.log` in `echo stdpath('data')` to see what is happening.
lua-debug indeed is not documented in nvim-dap and personally I never tried so maybe it doesn't work. It also uses the DAP protocol so in theory it should. I cannot give you any definitive answer on that.
